### PR TITLE
#26 Shuffle word bank and iterate through

### LINKED ISSUE #26: Reduce duplicate words across multiple rounds
When playing with eight players, words started repeating after about seven rounds. This is because the random word picker chooses words indiscriminately. It may be desirable to ensure that words are not repeated until the entire word bank has been exhausted. This is roughly how the Telestrations board game works, with word cards being discarded after use so that words are not repeated.

### PR DESCRIPTION
**Pull request by beamer159**
Resolves #26

### CODE REVIEW

**Comment by tannerkrewson** [comment]
this is a good idea, because it's similar to how the cards would work in real life. 

after a brief look at the code, i think the "deck" of words might be global to all concurrent games. which isn't really a big deal (maybe idk), but it's something ill need to test before merging in. 👍 no guarantees on when i have time for that but i will get around to it.

**Comment by tannerkrewson** [comment]
^that's my guess because a `new WordPacks` instance is defined globally https://github.com/tannerkrewson/drawphone/blob/master/app/round.js#L13

**Comment by beamer159** [comment]
I confirmed that the word packs are global across all games. This should be changed so that they are local to each game "room". Good catch.

**Comment by tannerkrewson** [comment]
i forgot about this because that fix was never made. reopen if you can against the new `dev` branch

**Pull request closed without merging**
