### PR TITLE
Removed non working game

### PR DESCRIPTION
**Pull request by alenros**
Sadly, The Fake Artist game is no longer online.

### CODE REVIEW

**Comment by alenros** [comment]
Removed non-working fake artist game.
Added a suggestion for another game.

**Comment by tannerkrewson** [comment]
Hey, thanks for pointing it out, and for your work on a new version of the game! However, looks like the link you added in your PR is incorrect, and `https://fake-artist.herokuapp.com/` gives me an error 🤔

**Comment by alenros** [comment]
You were right, the site was down for a couple of days since I exceeded the free quota on heroku with an experiment.
Try now 😁

**Comment by tannerkrewson** [comment]
https://rocketcrab.com/ babyyy!!

**Pull request closed without merging**
